urls.py
# -*- coding: utf-8 -*-
# vim:ts=4:expandtab:ai
# $Id$

from django.urls import path
from django.urls import re_path

from .views import (
    accept,
    authenticate,
    start,
    reinvite,
    end,
    cards,
    namelist,
    statistics,
    TheAPI,
)
from .auth import authn

app_name = 'esiidm'

urlpatterns = [
    path('reinvite', reinvite, name='reinvite'),
    path('cards/<int:hid>', cards, {'blank': False}, name='cards'),
    path('cards/<int:hid>/blank', cards, {'blank': True}, name='cards'),
    re_path(
        r'accept/(?P<token>[^/]+)/(?P<response>[YN])', accept, name='accept'
    ),
    path('accept/<token>', accept, name='accept'),
    path('authenticate', authenticate, name='authenticate'),
    path('accounts/login/', authenticate, name='login'),
    path('logout/', end, name='logout'),
    path('authn/<method>', authn, name='authn'),
    re_path('authn/(?P<method>[^/]+)/.*', authn, name='authn'),
    path('stats/', statistics, name='stats'),
    path('names/', namelist, name='names'),
    path('api/<sho>', TheAPI.as_view(), name='api'),
    path('api/<sho>/<esi>', TheAPI.as_view(), name='api'),
    path('api/<sho>/<esi>/<deltoken>', TheAPI.as_view(), name='api'),
    path('', start, name='start'),
]

templates/esiidm/auth_sources.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h3>
{% blocktrans %}
Please, select one of the following authentication methods
{% endblocktrans %}
</h3>

  <ul>
  {% for source in sources %}
    <li>
      <a href="{% url 'esiidm:authn' source.source %}">
        {% trans source.description %}
      </a>
    </li>
  {% endfor %}
  </ul>
{% endblock %}
{% comment %}
vim:ts=2:expandtab:ai
$Id$
{% endcomment %}

templates/esiidm/consent.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
{% blocktrans %}
<h3>Welcome to the European Student Card and Identifier management system</h3>
It is important the you consent that your personal information is processed
in the system before using it.<br>
This is what the system knows about you:<br>
{% endblocktrans %}
<ul>
  <li><strong>{% trans "Name" %}:</strong> {{ request.user.first_name }}</li>
  <li><strong>{% trans "Family name" %}:</strong> {{ request.user.last_name }}</li>
  <li><strong>{% trans "Email" %}:</strong> {{ request.user.email }}</li>
  {% if request.user.identifier %}
  <li><strong>{% trans "Identifier" %}:</strong> {{ request.user.identifier }}</li>
  {% endif %}
</ul>
<p>
{% blocktrans %}
Also, the system will create a link to the identification received vía
{{ source.description }} but no extra personal information will be stored.
{% endblocktrans %}
</p>
<p>
{% if request.user.is_student %}
{% blocktrans %}
Do you agree with the information being stored to provide you with an European
Student Card and Identifier?
{% endblocktrans %}
{% else %}
{% blocktrans %}
Do you agree with the information being stored to allow you access and
manage the system?
{% endblocktrans %}
{% endif %}
</p>
<a href="{% url 'esiidm:accept' token 'Y' %}" class="btn btn-success">{% trans "Yes" %}</a>
<a href="{% url 'esiidm:accept' token 'N' %}" class="btn btn-danger">{% trans "No" %}</a>
{% endblock %}
{% comment %}
vim:ts=2:expandtab:ai
$Id$
{% endcomment %}

templates/esiidm/expired.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h3>{% trans "Expired invitation" %}</h3>
{% if sent %}
{% blocktrans %}
The invitation you have used is expired.<br>
You will receive a fresh one you can use.
{% endblocktrans %}
{% else %}
{% blocktrans %}
The invitation you have used is expired.<br>
But sending a new one to the email address the system has for you, has failed.
{% endblocktrans %}
{% endif %}
{% endblock %}

{% comment %}
vim:ts=2:expandtab:ai
$Id$
{% endcomment %}

templates/esiidm/index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h3>{% trans "Welcome" %}</h3>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
      {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
{{ request.user.first_name }} {{ request.user.last_name }}
<a class="btn btn-danger" href="{% url 'esiidm:logout' %}">
{% trans "Close session" %}
</a><br>
Email: {{ request.user.email }}<br>
{% blocktrans %}
You can authenticate to the system using:
{% endblocktrans %}
<br>
<ul>
  {% for i in request.user.identifiers.all %}
  <li>{% trans i.source.description %}
  {% endfor %}
</ul><br>
{% blocktrans %}
If you want to use a new source for authenticating
{% endblocktrans %}
<a href="{% url 'esiidm:reinvite' %}">{% trans "request a new one" %}</a>
{% blocktrans %}
that will be sent to the above email address
{% endblocktrans %}
<br>
{% if request.user.is_staff %}
{% blocktrans %}
You have permission to manage the system
{% endblocktrans %}
<a href="{% url 'admin:index' %}">{% trans "via the admin panel" %}</a><br>
{% endif %}
{% if request.user.is_officer %}
{% blocktrans %}
You can manage students for the following HEI:
{% endblocktrans %}
<ul>
  {% for hei in request.user.HEIs %}
  <li>{{ hei }}
    <a href={% url 'esiidm:cards' hid=hei.id blank=False %}>{% trans "get cards in PDF" %}</a> or 
    <a href={% url 'esiidm:cards' hid=hei.id blank=True %}>{% trans "for preprinted backgrounds" %}</a>
  </li>
  {% endfor %}
</ul>
{% endif %}
{% if request.user.is_student %}
<emph>{% trans "Test presentation" %}</emph>
{% for c in request.user.cards.all %}
<div class="card col-bg-6 col-sm-12">
  <div class="card-body">
    <div class="media">
      <div class="media-body">  
        <h2 class="mt-0">{{ c.hei.name }}</h2>
      </div>
      <img src="data:image/png;base64,{{ c.myESCQR }}" height="150">
    </div>
    <div class="card-text">
      <h3>{{ c.student.first_name }} {{ c.student.last_name }}</h3>
      <strong>{% trans "Student Number" %}:</strong> 
      {{ c.hei.sho }}:{{ c.esi }}</br>
      <strong>{% trans "Card Number" %}:</strong>
      <a href="{{ c.myESCURL }}" class="btn btn-light">{{ c.esc }}</a>
    </div>
  </div>
</div>
{% endfor %}
{% endif %}
{% endblock %}

{% comment %}
vim:ts=2:expandtab:ai
$Id$
{% endcomment %}

templates/esiidm/load_cards.html
{% extends "admin/base_site.html" %}
{% load i18n %}
{% block content %}
    <div>
      <h2>{% trans "Student cards bulk load" %}</h2>
      <h3>
        {% blocktrans %}
        The CSV file MUST (RFC2119) have field names as columns on
        the first row.<br />
        Fields MAY (RFC2119) be in any order.
        {% endblocktrans %}
      </h3>
      <h3>
        {% blocktrans %}
        The CSV file MUST (RFC2119) have a minimum set of fields:
        {% endblocktrans %}
      </h3>
      <ul>
        <li>
          <strong>esi:</strong>
          {% trans "contains the student specific part of the ESI" %}
        </li>
        <li>
          <strong>first_name:</strong>
          {% trans "student's given name" %}
        </li>
        <li>
          <strong>last_name:</strong>
          {% trans "student's family name" %}
        </li>
        <li>
          <strong>email:</strong>
          {% trans "student's email" %}
        </li>
      </ul>
      <h3>
        {% blocktrans %}
        The rows MAY (RFC2119) also contain these optional fields:
        {% endblocktrans %}
      </h3>
      <ul>
        <li>
          <strong>identifier:</strong>
          {% trans "government issued identifier for the student" %}
        </li>
        <li>
          <strong>operation:</strong>
          {% trans "if present, value MUST (RFC 2119) be either" %}:
          <ul>
            <li>
              {% blocktrans %}
              D for deleting the card if it belongs to the student
              {% endblocktrans %}
            </li>
            <li>
              {% blocktrans %}
              C for creating a new card, this is the default if absent
              {% endblocktrans %}
            </li>
          </ul>
        </li>
      </ul>
      <p>
      {% blocktrans %}
      Persons are created as needed and receive an invitation over email
      requesting consent.
      {% endblocktrans %}
      </p>
    </div>
    <div>
      <form action="." method="POST" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        {% trans "Please, make sure you select the right delimiter." %}
        <button class="button" index="0" type="submit">
          {% trans "Upload CSV" %}
        </button>
      </form>
    </div>
    <br />

{% endblock %}

templates/esiidm/load_heis.html
{% extends "admin/base_site.html" %}
{% load i18n %}
{% block content %}
    <div>
      <h2>{% trans "HEI bulk load" %}</h2>
      <h3>
        {% blocktrans %}
        The CSV file MUST (RFC2119) have field names as columns on
        the first row.<br />
        Fields MAY (RFC2119) be in any order.
        {% endblocktrans %}
      </h3>
      <h3>
        {% blocktrans %}
        The CSV file MUST (RFC2119) have a minimum set of fields:
        {% endblocktrans %}
      </h3>
      <ul>
        <li>
          <strong>name:</strong>
          {% trans "HEI name" %}
        </li>
        <li>
          <strong>country:</strong>
          {% trans "HEI country ISO two letter code" %}
        </li>
        <li>
          <strong>sho:</strong>
          {% trans "SCHAC Home Organization (HEI Internet domain)" %}
        </li>
        <li>
          <strong>manager:</strong>
          {% trans "email address for the main HEI officer" %}
        </li>
      </ul>
      <h3>
        {% blocktrans %}
        The rows MAY (RFC2119) also contain these optional fields:
        {% endblocktrans %}
      </h3>
      <ul>
        <li>
          <strong>pic:</strong>
          {% trans "HEI PIC code (required for ESC)" %}
        </li>
        <li>
          <strong>euc:</strong>
          {% trans "HEI EUC code" %}
        </li>
        <li>
          <strong>erc:</strong>
          {% trans "HEI Erasmus code" %}
        </li>
        <li>
          <strong>oid:</strong>
          {% trans "HEI Erasmus OID" %}
        </li>
        <li>
          <strong>url:</strong>
          {% trans "HEI main web page" %}
        </li>
        <li>
          <strong>termstart:</strong>
          {% trans "month when term starts (1 through 12)" %}
        </li>
        <li>
          <strong>first_name:</strong>
          {% trans "Main officer's given name" %}
        </li>
        <li>
          <strong>last_name:</strong>
          {% trans "Main officer's family name" %}
        </li>
      </ul>
      <p>
        {% blocktrans %}
        If first_name and last_name are present,
        the person is created in the system if needed.<br>
        If they are not, there MUST exist a person with the provided email.
        {% endblocktrans %}
        <br/>
        {% blocktrans %}
        Persons receive an invitation via email for activating the account.
        {% endblocktrans %}
      </p>
    </div>
    <div>
      <form action="." method="POST" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        {% trans "Please, make sure you select the right delimiter." %}
        <button class="button" index="0" type="submit">
          {% trans "Upload CSV" %}
        </button>
      </form>
    </div>
{% endblock %}

templates/esiidm/load_officers.html
{% extends "admin/base_site.html" %}
{% load i18n %}
{% block content %}
    <div>
      <h2>{% trans "Officer bulk load" %}</h2>
      <p>
      {% blocktrans %}
      An officer is just a person that has special status and is linked to
      a HEI (or more) whose cards and students is authorised to manage.
      {% endblocktrans %}
      <br/>
      {% if request.user.is_superuser %}
      {% blocktrans %}
      The first officer for a HEI may be loaded as an unlinked person and the link
      is later established when the HEI is created.
      {% endblocktrans %}
      {% endif %}
      </p>
      <h3>
        {% blocktrans %}
        The CSV file MUST (RFC2119) have field names as columns on
        the first row.<br />
        Fields MAY (RFC2119) be in any order.
        {% endblocktrans %}
      </h3>
      <h3>
        {% blocktrans %}
        The CSV file MUST (RFC2119) have a minimum set of fields:
        {% endblocktrans %}
      </h3>
      <ul>
        <li>
          <strong>first_name:</strong>
          {% trans "officer's given name" %}
        </li>
        <li>
          <strong>last_name:</strong>
          {% trans "officer's family name" %}
        </li>
        <li>
          <strong>email:</strong>
          {% trans "officer's email" %}
        </li>
      </ul>
      <h3>
        {% blocktrans %}
        The rows MAY (RFC2119) also contain these optional fields:
        {% endblocktrans %}
      </h3>
      <ul>
        <li>
          <strong>identifier:</strong>
          {% trans "government issued identifier for the person" %}
        </li>
        {% if request.user.is_superuser %}
        <li>
          <strong>sho:</strong>
          {% trans "officer's HEI schacHomeOrganization" %}
        </li>
        <li>
          <strong>pic:</strong>
          {% trans "officer's HEI PIC code" %}
        </li>
        <li>
          <strong>euc:</strong>
          {% trans "officer's HEI EUC code" %}
        </li>
        <li>
          <strong>erc:</strong>
          {% trans "officer's HEI ERC code" %}
        </li>
        <li>
          <strong>oid:</strong>
          {% trans "officer's HEI OID code" %}
        </li>
        {% endif %}
      </ul>
      <p>
        {% if request.user.is_superuser %}
        {% blocktrans %}
        Only one of SHO, PIC, EUC, ERC or OID is required for linking
        the officer to the HEI.
        {% endblocktrans %}
        <br/>
        {% blocktrans %}
        If there is no HEI, the person is created in the system
        with needed privileges but no associated HEI.
        {% endblocktrans %}
        <br/>
        {% endif %}
        {% blocktrans %}
        Persons receive an invitation via email for activating the account.
        {% endblocktrans %}
      </p>
    </div>
    <div>
      <form action="." method="POST" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        {% trans "Please, make sure you select the right delimiter." %}
        <button class="button" index="0" type="submit">
          {% trans "Upload CSV" %}
        </button>
      </form>
    </div>
    <br />

{% endblock %}

templates/esiidm/not_consent.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
{% blocktrans %}
<h3>Processing of personal information rejected</h3>
Your declination of consent has been registered. Thank you.<br>
Please note that you will not be able to use the system.<br>
{% endblocktrans %}
{% endblock %}

{% comment %}
vim:ts=2:expandtab:ai
$Id$
{% endcomment %}

templates/esiidm/statistics.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h3>
{% trans "Usage statistics" %}
</h3>
  {% if heicount is not None %}
  <p>
  <strong>{% trans "Number of HEIs" %}:</strong> {{ heicount }}
  <strong>{% trans "Number of cards" %}:</strong> {{ cardcount }}
  <strong>{% trans "Number of authentications" %}:</strong> {{ authcount }}
  </p>
  {% endif %}
  <table class="table table-responsive table-striped table-condensed">
    <tr>
      <th>{% trans "HEI name" %}</th>
      <th>{% trans "students" %}</th>
      <th>{% trans "authentications" %}</th>
    </tr>
    <tbody>
    {% for h in heis %}
    <tr>
      <td style="text-align: left">{{ h.name }} </td>
      <td style="text-align: center">{{ h.studentcards.count }}</td>
      <td style="text-align: center">{{ h.authentications.count }}</td>
    </tr>
  {% empty %}
    <tr>
      <td colspan=2 style="text-align: center">
        {% trans "Empty listing" %}
      </td>
      </tr>
  {% endfor %}
    </tbody>
  </table>
<p>
{% endblock %}
{% comment %}
vim:ts=2:expandtab:ai
$Id$
{% endcomment %}

templates/esiidm/unknown.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h3>{% trans "Welcome" %}</h3>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
      {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
{% trans "You have to" %} 
<a href="{% url 'esiidm:authenticate' %}" class="btn btn-success">
  {% trans "authenticate yourself" %}
</a>
{% trans "to use the system." %}
{% endblock %}

{% comment %}
vim:ts=2:expandtab:ai
$Id$
{% endcomment %}